-- AlterTable
ALTER TABLE "Registration" ALTER COLUMN "dateTime" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Schedule" ALTER COLUMN "date" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "startTime" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "endTime" SET DATA TYPE TIMESTAMPTZ;
